package com.roberto.snow.command;

import com.roberto.snow.Snow;
import com.roberto.snow.arena.*;
import com.roberto.snow.generator.GeneratorType;
import com.roberto.snow.util.Text;
import org.bukkit.command.*;
import org.bukkit.entity.Player;
import java.util.*;

public final class SnowCommand implements CommandExecutor, TabCompleter {
    private final Snow plugin; public SnowCommand(Snow plugin){this.plugin=plugin;}
    public boolean onCommand(CommandSender sender,Command command,String label,String[] args){
        if(args.length==0){help(sender);return true;}String sub=args[0].toLowerCase();
        if("join".equals(sub)){player(sender);if(!(sender instanceof Player))return true;if(args.length<2){sender.sendMessage("&cUso: /bw join <arena>");return true;}Player p=(Player)sender;if(plugin.getArenaManager().getArena(p)!=null){plugin.getMessages().send(p,"already-in-arena");return true;}if(!plugin.getArenaManager().join(p,args[1]))plugin.getMessages().send(p,"arena-full",Collections.singletonMap("%arena%",args[1]));else plugin.getMessages().send(p,"joined",map("%player%",p.getName(),"%arena%",args[1]));return true;}
        if("leave".equals(sub)){leave(sender);return true;} if("list".equals(sub)||"arenalist".equals(sub)){list(sender);return true;}
        if("gui".equals(sub)){if(sender instanceof Player)plugin.getShopService().openShop((Player)sender);return true;} if("upgrades".equals(sub)){if(sender instanceof Player)plugin.getShopService().openUpgrades((Player)sender);return true;}
        if("create".equals(sub)){if(!admin(sender))return true;if(args.length<3){sender.sendMessage("§cUso: /bw create <arena> <solo|doubles|3v3v3v3|4v4v4v4>");return true;}ArenaMode mode=ArenaMode.parse(args[2]);if(mode==null){sender.sendMessage("§cModo inválido.");return true;}plugin.getArenaManager().create(args[1],mode);sender.sendMessage("§1[§bSnow§1] §fArena §b"+args[1]+" §fcriada.");return true;}
        if("setspawn".equals(sub)||"setbed".equals(sub)||"generator".equals(sub)){setup(sender,sub,args);return true;}
        if("setworld".equals(sub)){if(!admin(sender))return true;if(args.length<3){sender.sendMessage("§cUso: /bw setworld <arena> <mundo>");return true;}if(plugin.getArenaManager().getArena(args[1])==null){plugin.getMessages().send(sender,"arena-not-found",Collections.singletonMap("%arena%",args[1]));return true;}plugin.getConfig().set("arenas."+args[1]+".world",args[2]);plugin.saveConfig();sender.sendMessage("§1[§bSnow§1] §fMundo de reset configurado.");return true;}
        if("reload".equals(sub)){if(!admin(sender))return true;plugin.reloadSnow();sender.sendMessage("§1[§bSnow§1] §fConfigurações recarregadas.");return true;}
        if("start".equals(sub)||"setup".equals(sub)||"setshop".equals(sub)||"setupshop".equals(sub)||"setupgrade".equals(sub)||"setwaitingspawn".equals(sub)||"setspectatorpos".equals(sub)||"settype".equals(sub)||"setmaxinteam".equals(sub)||"setbuildheight".equals(sub)||"setkilldropsloc".equals(sub)||"autocreateteams".equals(sub)||"createteam".equals(sub)||"removeteam".equals(sub)||"addgenerator".equals(sub)||"removegenerator".equals(sub)||"save".equals(sub)||"build".equals(sub)||"clonearena".equals(sub)||"delarena".equals(sub)||"enable".equals(sub)||"disable".equals(sub)||"arenagroup".equals(sub)||"setlobby".equals(sub)||"npc".equals(sub)||"level".equals(sub)||"lang".equals(sub)||"stats".equals(sub)||"prestige".equals(sub)||"quests".equals(sub)||"teleporter".equals(sub)||"tpstaff".equals(sub)){sender.sendMessage("§1[§bSnow§1] §fO comando §b"+sub+" §festá registrado na camada de compatibilidade. Use §b/bw help §fpara a alternativa Snow disponível.");return true;}
        plugin.getMessages().send(sender,"unknown-command");return true;
    }
    private void setup(CommandSender sender,String sub,String[] args){if(!admin(sender))return;if(!(sender instanceof Player)){plugin.getMessages().send(sender,"player-only");return;}if(args.length<3){sender.sendMessage("§cUso: /bw "+sub+" <arena> "+("generator".equals(sub)?"<iron|gold|diamond|emerald>":"<team>"));return;}Arena arena=plugin.getArenaManager().getArena(args[1]);if(arena==null){plugin.getMessages().send(sender,"arena-not-found",Collections.singletonMap("%arena%",args[1]));return;}Player p=(Player)sender;if("setspawn".equals(sub))plugin.getArenaManager().setSpawn(arena,args[2],p.getLocation());else if("setbed".equals(sub))plugin.getArenaManager().setBed(arena,args[2],p.getLocation().getBlock().getLocation());else {GeneratorType type=GeneratorType.parse(args[2]);if(type==null){sender.sendMessage("§cGerador inválido.");return;}plugin.getArenaManager().addGenerator(arena,type,p.getLocation().getBlock().getLocation());}sender.sendMessage("§1[§bSnow§1] §fPosição salva.");}
    private void leave(CommandSender sender){if(sender instanceof Player){Player p=(Player)sender;if(plugin.getArenaManager().getArena(p)!=null){plugin.getArenaManager().leave(p,false);plugin.getScoreboards().clear(p);plugin.getMessages().send(p,"left",Collections.singletonMap("%player%",p.getName()));}}}
    private void list(CommandSender sender){sender.sendMessage("§1[§bSnow§1] §fArenas:");for(Arena a:plugin.getArenaManager().getArenas())sender.sendMessage(" §b"+a.getId()+" §f"+a.getPlayers().size()+"/"+a.getMode().getMaxPlayers()+" §7("+a.getState()+")");}
    private void help(CommandSender sender){sender.sendMessage(Text.color("&1[&bSnow&1] &f/bw join <arena>, &b/bw leave&f, &b/bw list&f, &b/bw gui&f, &b/bw upgrades"));if(sender.hasPermission("snow.admin"))sender.sendMessage(Text.color("&fAdmin: &b/bw create&f, &b/bw setworld&f, &b/bw setspawn&f, &b/bw setbed&f, &b/bw generator&f, &b/bw reload"));}
    private void player(CommandSender sender){if(!(sender instanceof Player))plugin.getMessages().send(sender,"player-only");} private boolean admin(CommandSender sender){if(sender.hasPermission("snow.admin"))return true;plugin.getMessages().send(sender,"no-permission");return false;}
    private Map<String,String> map(String a,String b,String c,String d){Map<String,String> result=new HashMap<String,String>();result.put(a,b);result.put(c,d);return result;}
    public List<String> onTabComplete(CommandSender sender,Command command,String alias,String[] args){if(args.length==1)return prefix(Arrays.asList("join","leave","list","gui","upgrades","create","setspawn","setbed","generator","reload","setup","stats","teleporter"),args[0]);if(args.length==2&&(args[0].equalsIgnoreCase("join")||args[0].equalsIgnoreCase("setspawn")||args[0].equalsIgnoreCase("setbed")||args[0].equalsIgnoreCase("generator"))){List<String> names=new ArrayList<String>();for(Arena a:plugin.getArenaManager().getArenas())names.add(a.getId());return prefix(names,args[1]);}return Collections.emptyList();}
    private List<String> prefix(List<String> all,String value){List<String> out=new ArrayList<String>();for(String s:all)if(s.startsWith(value.toLowerCase()))out.add(s);return out;}
}
